version: '3.7'

services:
  sna-backend:
    container_name: ${PROJECT_NAME}-backend
    build:
      context: .
      target: ${NODE_ENV}
    links:
      - "sna-db:database"
    volumes:
      - .:/usr/src/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run ${START_COMMAND}
    env_file:
      - .env
    depends_on:
      - sna-db
    tty: true

  sna-db:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    expose:
      - 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
